#!/usr/bin/env ruby

require_relative '../lib/minim_locales'

require 'thor'

class CLI < Thor
  desc "update", "Runs the update_intermediate_locales, update_public_locales and transifex_export commands in that order"
  def update
    # MinimLocales.update
    puts 'update'
  end

  desc "update_intermediate_locales", "Updates the intermediate databases for every supported locale"
  def update_intermediate_locales
    # MinimLocales.update_intermediate_locales
    puts 'update_intermediate_locales'
  end

  desc "update_public_locales", "Updates the public locales using the latest translations from transifex and google translate"
  def update_public_locales
    # MinimLocales.update_public_locales
    puts 'update_public_locales'
  end

  desc "transifex_export", "Uploads the strings contained in the english intermediates file to Transifex"
  def transifex_export
    # MinimLocales.transifex_export
    puts 'transifex_export'
  end

  desc "verify", "Verifies whether or not there are translation files that do not match or if there are English files that have not uet been translated."
  def verify
    # MinimLocales.verify
    puts 'verify'
  end
end

CLI.start(ARGV)
